---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarrnew
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
# For hardlinks to work across containers the volumes must match with sonarr and be a top level directory
    volumes:
      - /home/gandalf/sonarrnew:/config
      - /media/8tb/data:/data
    ports:
      - 9292:9292
    restart: unless-stopped
