---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarrnew
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /home/gandalf/sonarrnew:/config
      - /media/8tb/data:/data           # replicate this line in each docker container that will use hardlinks
    ports:
      - 9292:9292
    restart: unless-stopped
